name: Synchronize Thcrap Chinese branch patch file.
on:
    workflow_dispatch:
    schedule:
        - cron: '* 0/6 * * *'
jobs:
  CN_Patch_Sync_Timing_or_Manually:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull the latest patch file from the main source server (https://srv.thpatch.net/lang_zh-hans/)
      run: |
        cd ./TimingSync
        sudo wget -tries=10 https://srv.thpatch.net/lang_zh-hans/files.js
        sudo chmod +x ./PatchFileSync
        ./PatchFileSync repo_files.js files.js
        sudo rm -f repo_files.js
        sudo cp files.js ../lang_zh-hans/files.js
        sudo mv files.js repo_files.js
            
    - name: Pull the latest hook config files from thcrap-tsa（https://github.com/thpatch/thcrap-tsa）
      run: |
        svn checkout https://github.com/thpatch/thcrap-tsa/trunk/aero
        svn checkout https://github.com/thpatch/thcrap-tsa/trunk/base_tasofro
        svn checkout https://github.com/thpatch/thcrap-tsa/trunk/base_tsa
        sudo rm -rf ./aero/.svn ./base_tasofro/.svn ./base_tsa/.svn
            
    - name: Push the patch file to the GitHub repository.
      env:
          GITHUB_TOKEN: ${{ secrets.SYNCHONIZE_TOKEN }}
      run: |
        git config user.name "ROCO2021"
        git config user.email "1401548627@qq.com" 
        git add .
        cd ./TimingSync
        sudo chmod +x ./GenerateCommitText.sh
        git commit -m $(./GenerateCommitText.sh)
        git push https://$GITHUB_TOKEN@github.com/ROCO-freedom/Thpatch_CN_Mirror.git
        
    - name: Push the latest file to Coding repository.
      uses: wearerequired/git-mirror-action@v1.2.0
      env:
        SSH_PRIVATE_KEY: ${{ secrets.CODING_RSA_PRIVATE_KEY }}
      with:
        # 来源仓库
        source-repo: "git@github.com:ROCO-freedom/Thpatch_CN_Mirror.git"
        # 目标仓库
        destination-repo: "git@e.coding.net:thpatch-cn/thcrapcn/Thpatch_CN_Patchfiles_Mirror.git"
