name: Synchronize Thcrap Chinese branch patch file.
on:
    workflow_dispatch:
    schedule:
        - cron: '* 0/6 * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull the latest patch file from the main source server (https://srv.thpatch.net/lang_zh-hans/)
      run: |
        cd ./TimingSync
        sudo apt-get update
        sudo apt-get install wget
        sudo wget -tries=10 https://srv.thpatch.net/lang_zh-hans/files.js
        sudo chmod +x ./PatchFileSync
        ./PatchFileSync repo_files.js files.js
        sudo rm -f repo_files.js
        sudo cp files.js ../lang_zh-hans/files.js
        sudo mv files.js repo_files.js
            
    - name: Pull the latest hook config files from thcrap-tsa（https://github.com/thpatch/thcrap-tsa）
      run: |
        sudo apt-get update
        sudo apt-get install subversion
        svn checkout https://github.com/thpatch/thcrap-tsa/trunk/aero
        svn checkout https://github.com/thpatch/thcrap-tsa/trunk/base_tasofro
        svn checkout https://github.com/thpatch/thcrap-tsa/trunk/base_tsa
            
    - name: Push the patch file to the GitHub repository.
      env:
          GITHUB_TOKEN: ${{ secrets.SYNCHONIZE_TOKEN }}
      run: |
        git config user.name "ROCO2021"
        git config user.email "1401548627@qq.com" 
        git add .
        sudo chmod +x ./GenerateCommitText.sh
        ./GenerateCommitText.sh | git commit -m
        git push https://$GITHUB_TOKEN@github.com/ROCO-freedom/Thpatch_CN_Mirror.git